name: Run and Check Tests

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run NestJS tests
        id: run-tests
        run: npm run test

    outputs:
      test-result: ${{ failed }}

  check-tests:
    name: Check tests
    runs-on: ubuntu-latest

    needs: run-tests

    steps:
      - name: Check tests
        run: echo "Test result ${{ needs.run-tests.outputs.test-result }}"
